.PHONY: all clean

all:	part1.c part2.c

part1.c:
	@echo "Part 1"
	gcc -O3 part1.c -o part1.out
	./part1.out


part2.c:
	@echo "Part 2"
	gcc -O3 part2.c -o part2.out
	./part2.out

clean:
	@echo "Cleaning"
	rm *.out
	rm part*.output
